server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: micro-usuarios
          uri: lb://usuarios
          predicates:
            - Path=/usuarios/**
        - id: micro-pizzasRead
          uri: lb://pizzasRead
          predicates:
            - Path=/pizzasRead/**
        - id: micro-pizzasWrite
          uri: lb://pizzasWrite
          predicates:
            - Path=/pizzasWrite/**