# HTTP Server
server:
  port: 8888

spring:
  application:
    name: config-server
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.hiberus.com/jmora/introSpringCloud-Configuracion.git
          default-label: master